#!/bin/bash
#Gunakan tools ini Dengan Bijak!
clear
figlet "Mr putra"
echo "_____________________________"
echo "Author: putra"
echo "Kontak: 082264330973"
echo
echo "[Pilih Menunya]"
echo "[1] Dark fb"
echo "[2] Stabilkan Jaringan"
echo "[3] Install bahannya"
echo
read -p [Pilih nomor]>>>" pill
#batas gan
if [$ pill = "1"]
then echo " Sedang Menginstall...." ; sleep 2
git clone https://github.com/M4sUkhr13x/dark fb
cd dark-fb
python2 da.py
echo "Menginstall Selesai[√]"
fi
#batas gan
if [$ pill = "2"]
then
ping -s 900
fi
#batas gan
if [$ pill = "3"]
then
echo "Sedang Menginstall bahan...." ;sleep 2
pkg update && pkg upgrade
pkg install nano
pkg install figlet
pkg install git
pkg instal toilet
pip2 install requests mechanize
echo "Menginstall Selesai[√]"
fi
#batas gan
if [$ pill = "0"]
then
echo "Thanks,Jangan Lupa Balik Lagi"
exit
fi
